#!/bin/bash
# driver.sh — Unattended Development System Driver v1.2.0
# Auto-generated by unattended-dev-system skill
# Enhanced with security validation, error handling, and platform support
# Project: DF-FanYi
# Language: Python
# Framework: pytest

set -euo pipefail

# Default values (overridden by config.json at runtime)
DRY_RUN=false
CLI_DRY_RUN=false
FAILS=0
CURRENT_PROVIDER=0

# Parse CLI args (--dry-run before anything else; CLI wins over config)
for _arg in "$@"; do
    case "$_arg" in
        --dry-run) DRY_RUN=true; CLI_DRY_RUN=true ;;
        --debug) set -x ;;
    esac
done

# ============================================
# LOGGING (must be defined before use)
# ============================================

# A helper to write logs even before $LOG exists
_log_path() {
    if [ -n "${LOG_DIR:-}" ] && [ -d "$LOG_DIR" ]; then
        echo "$LOG_DIR/driver.log"
    else
        echo "/tmp/driver-DF-FanYi.log"
    fi
}

log() {
    local p; p=$(_log_path)
    echo "[$(date '+%F %T')] $*" >> "$p"
    echo "[$(date '+%F %T')] $*"
}

log_error() {
    local p; p=$(_log_path)
    echo "[$(date '+%F %T')] ❌ $*" >> "$p"
    echo "[$(date '+%F %T')] ❌ $*" >&2
}

log_success() {
    local p; p=$(_log_path)
    echo "[$(date '+%F %T')] ✅ $*" >> "$p"
    echo "[$(date '+%F %T')] ✅ $*"
}

# ============================================
# SECURITY VALIDATION
# ============================================

# Validate and resolve a path: must exist, be a directory, and contain no
# traversal segments. (Defends against path traversal without wrongly
# rejecting legitimate project roots outside \$HOME, e.g. /tmp, /opt.)
validate_path() {
    local path="$1" resolved
    resolved=$(realpath "$path" 2>/dev/null) || {
        log_error "Path does not resolve: $path"
        return 1
    }
    [ -d "$resolved" ] || {
        log_error "Path is not a directory: $resolved"
        return 1
    }
    case "$resolved" in
        *"/../"*|*"/./"*)
            log_error "Path contains traversal segments: $resolved"
            return 1 ;;
    esac
    return 0
}

# Validate an AI command string before it is executed (defends against injection).
validate_ai_command() {
    local cmd="$1" exe
    # Extract the executable (first token) and require it be a known binary
    exe=$(printf '%s' "$cmd" | awk '{print $1}')
    case "$exe" in
        pi|bun|npx|python3|python|node|bash|sh|npm|go|cargo|mvn|timeout|echo|true|false) ;;
        *)
            log_error "AI command must start with a known executable, got: $exe"
            return 1 ;;
    esac
    # Reject shell metacharacters that could enable injection (grep -E keeps
    # them literal, unlike case patterns where '|' is a separator).
    if printf '%s' "$cmd" | grep -qE '(\$\(|[;&|]|`|/dev/|>|<)'; then
        log_error "Rejected AI command with dangerous characters: $cmd"
        return 1
    fi
    return 0
}

# ============================================
# CONFIG LOADING (reads .unattended/config.json at runtime)
# ============================================

# load_cfg <dotted-key> <default>  → echoes the value from config.json
load_cfg() {
    local key="$1" default="$2" val
    val=$(python3 -c "
import json, sys
try:
    d = json.load(open(sys.argv[1]))
    for k in sys.argv[2].split('.'):
        d = d[k]
    print(str(d).lower() if isinstance(d, bool) else d)
except Exception:
    sys.exit(1)
" "$REPO/.unattended/config.json" "$key" 2>/dev/null)
    echo "${val:-$default}"
}

# ============================================
# CONFIGURATION (resolved after config.json loads)
# ============================================

REPO=$(realpath "/home/wu/DF-FanYi")

LOG_DIR="$REPO/.unattended"
LOG="$LOG_DIR/driver.log"
STATUS="$LOG_DIR/status.yaml"
TASKS_DIR="$LOG_DIR/tasks"
CHECKPOINT_DIR="$LOG_DIR/checkpoints"

# Create directories
mkdir -p "$LOG_DIR" "$TASKS_DIR/todo" "$TASKS_DIR/doing" "$TASKS_DIR/done" "$CHECKPOINT_DIR"

# AI Providers (configurable via config.json, else rendered default)
PROVIDERS=("pi-primary")
PROVIDER_COUNT=${#PROVIDERS[@]}

# Test command (configurable)
TEST_COMMAND="python3 -m pytest tests/ -q"

# Git configuration (runtime-overridable)
GIT_AUTO_PUSH=$(load_cfg "git.auto_push" "true")
COMMIT_PREFIX=$(load_cfg "git.commit_message_format" "chore(driver)")

# Timeout settings (runtime-overridable)
DRIVER_TIMEOUT=$(load_cfg "driver.timeout" "7200")
ZERO_OUTPUT_FUSE=$(load_cfg "driver.zero_output_fuse" "900")
# CLI --dry-run wins over config; otherwise honour config
if [ "$CLI_DRY_RUN" != "true" ]; then
    DRY_RUN=$(load_cfg "driver.dry_run" "$DRY_RUN")
fi

# ============================================
# UTILITY FUNCTIONS
# ============================================

cur_provider() {
    echo "${PROVIDERS[$CURRENT_PROVIDER]}"
}

# Check if tests pass
tests_pass() {
    (cd "$REPO" && timeout 600 $TEST_COMMAND >/dev/null 2>&1)
}

# Check if all tasks done (based on actual task dirs, not a hardcoded count)
all_done() {
    local done total
    total=$(ls "$REPO/docs/tickets"/ticket-*.md 2>/dev/null | wc -l)
    [ "$total" -eq 0 ] && return 1
    done=$(grep -l -e "^## 状态: done" -e "^> .*状态：done" "$REPO/docs/tickets"/ticket-*.md 2>/dev/null | wc -l)
    [ "$done" -ge "$total" ]
}

# Get current round output
round_output() {
    local mark; mark=$(cat "$LOG_DIR/.round_mark" 2>/dev/null || echo "0")
    tail -c +$((mark+1)) "$LOG" 2>&1
}

# Detect quota hit
quota_hit() {
    round_output | grep -qiE "quota|额度|429|rate.?limit|insufficient|exceeded|余额不足|balance"
}

# Detect context overflow
ctx_hit() {
    round_output | grep -qiE "context.{0,20}(length|limit|window|overflow)|maximum context|too long|token limit"
}

# Detect zero output
zero_output() {
    local mark; mark=$(cat "$LOG_DIR/.round_mark" 2>/dev/null || echo "0")
    local current_size; current_size=$(stat -c %s "$LOG" 2>&1)
    [ "$current_size" -le "$mark" ]
}

# ============================================
# LOOP-BASED STALL FUSE (best practice)
# ============================================
# spawn_stall_watchdog <ai_pid> <log_file> [silent_seconds] [check_interval]
#
# Background loop that watches a spawned AI process and kills its tree if the
# driver log shows NO growth AND the process shows NO CPU change for
# `silent_seconds` (default 900). Never blocks the main loop.
#
# ⚠️  WHY LOOP, NOT CHECK-ONCE (real-world incident):
# A single `sleep 900; if no-output ...` check misses the classic
# "wrote output first, then hung" stall (e.g. a network/TTY hang after an
# early success). The one-shot check runs, finds output, and never re-arms;
# nothing else ever looks again, so `wait "$pid"` blocks FOREVER and the
# whole pipeline freezes — symptom: token quota stops moving and progress
# reports stay identical every cycle. Loop-based detection re-arms every
# `check_interval` seconds and catches stalls that begin AFTER the first check.
#
# USE ONLY when the AI command must run in the BACKGROUND (e.g. `pi ... &`
# + `wait`). The default foreground `timeout "$DRIVER_TIMEOUT" ...` path
# (see Main Loop below) already covers stalls via the timeout, so it does
# NOT need this.
spawn_stall_watchdog() {
    local pid=$1 log=$2
    local silent=${3:-900} interval=${4:-120}
    local idle_max=$((silent / interval)); [ "$idle_max" -lt 1 ] && idle_max=1
    (
        local last_size last_cpu new_size new_cpu idle=0
        last_size=$(stat -c %s "$log" 2>/dev/null || echo 0)
        last_cpu=$(awk '{print $14+$15}' "/proc/$pid/stat" 2>/dev/null || echo 0)
        while kill -0 "$pid" 2>/dev/null; do
            sleep "$interval"
            new_size=$(stat -c %s "$log" 2>/dev/null || echo 0)
            new_cpu=$(awk '{print $14+$15}' "/proc/$pid/stat" 2>/dev/null || echo 0)
            if [ "$new_size" = "$last_size" ] && [ "$new_cpu" = "$last_cpu" ]; then
                idle=$((idle + 1))
                if [ "$idle" -ge "$idle_max" ]; then
                    log_error "⏳ Stall fuse tripped: no log growth & no CPU for ${silent}s (pid $pid)"
                    # 挂起进程可能无子进程，pkill 会返回非零；子 shell 继承 set -e，
                    # 必须 || true 兜底，否则 errexit 提前退出、kill 永不执行 → 假死进程仍存活
                    pkill -TERM -P "$pid" 2>/dev/null || true
                    kill -TERM "$pid" 2>/dev/null || true
                    break
                fi
            else
                idle=0
            fi
            last_size=$new_size
            last_cpu=$new_cpu
        done
    ) &
}

# Save status
save_status() {
    cat > "$STATUS" << EOF
status: "$1"
provider: "$(cur_provider)"
provider_index: $CURRENT_PROVIDER
failures: $FAILS
last_update: "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
tasks_done: $(ls "$TASKS_DIR/done/" 2>/dev/null | wc -l)
tasks_total: $(( $(ls "$TASKS_DIR"/todo/ 2>/dev/null | wc -l) + $(ls "$TASKS_DIR"/doing/ 2>/dev/null | wc -l) + $(ls "$TASKS_DIR/done/" 2>/dev/null | wc -l) ))
EOF
}

# Save checkpoint
save_checkpoint() {
    local phase="$1" message="$2" next="$3" context="$4"
    local timestamp checkpoint_file
    timestamp=$(date -u +%Y%m%d_%H%M%S)
    checkpoint_file="$CHECKPOINT_DIR/checkpoint_${timestamp}.json"

    cat > "$checkpoint_file" << EOF
{
  "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "phase": "$phase",
  "message": "$message",
  "next": "$next",
  "provider": "$(cur_provider)",
  "context": "$context"
}
EOF

    log_success "Checkpoint saved: $phase - $message"
}

# Auto commit and push
auto_commit() {
    # Correct flag: git status --porcelain (not git --porcelain)
    if [ -n "$(git -C "$REPO" status --porcelain 2>/dev/null)" ]; then
        local message="$1" timestamp
        timestamp=$(date '+%F %T')

        cd "$REPO" || return 1

        git add -A
        git commit -m "${COMMIT_PREFIX} ${timestamp}: ${message}" --allow-empty -q

        if [ "$GIT_AUTO_PUSH" = "true" ]; then
            git push -q origin HEAD 2>&1 && log_success "Pushed to GitHub" || log_error "Push failed"
        else
            log_success "Committed locally (auto_push disabled)"
        fi
    fi
}

# ============================================
# MAIN LOOP
# ============================================

# Validate repository path (S-003) before proceeding
if [ ! -d "$REPO" ]; then
    log_error "Repository path does not exist: $REPO"
    exit 1
fi
validate_path "$REPO" || exit 1

# Validate AI command (S-002) once at startup
if ! validate_ai_command "pi --print --no-session --mode text --model router/L2 -p '无人值守驱动. 成本铁律: 只读当前工单文件与它点名的文件+必要源码, 禁止通读工程书/全库/无关源码, 每轮 token 都是订阅额度. 读取 docs/tickets 目录,找到编号最小的状态为 pending 且其 Blocked by 引用的工单全部 done 的工单. 严格按该工单实现,遵循 docs/specs 与工程书强制禁止事项,测试驱动开发. 完成后把该工单状态行改为 done,复制该文件到 .unattended/tasks/done 目录,运行 python3 -m pytest tests/ -q 确认全绿,然后 git add -A 并 git commit. 若无可做工单,只输出一行等待原因,禁止修改任何代码禁止提交'"; then
    log_error "AI command failed validation. Fix pi --print --no-session --mode text --model router/L2 -p '无人值守驱动. 成本铁律: 只读当前工单文件与它点名的文件+必要源码, 禁止通读工程书/全库/无关源码, 每轮 token 都是订阅额度. 读取 docs/tickets 目录,找到编号最小的状态为 pending 且其 Blocked by 引用的工单全部 done 的工单. 严格按该工单实现,遵循 docs/specs 与工程书强制禁止事项,测试驱动开发. 完成后把该工单状态行改为 done,复制该文件到 .unattended/tasks/done 目录,运行 python3 -m pytest tests/ -q 确认全绿,然后 git add -A 并 git commit. 若无可做工单,只输出一行等待原因,禁止修改任何代码禁止提交' in config."
    exit 1
fi

cd "$REPO" || exit 1
log "=== UNATTENDED DRIVER STARTED v1.2.0 ==="
log "Project: DF-FanYi"
log "Providers: ${PROVIDER_COUNT} configured"
log "Test command: $TEST_COMMAND"
log "Mode: $([ "$DRY_RUN" = true ] && echo '(DRY RUN)' || echo '(LIVE)')"
log "Platform: $(uname -s)"
log "Timeout: $DRIVER_TIMEOUT s | Zero-output fuse: $ZERO_OUTPUT_FUSE s"

# Main loop
ROUND=0
while true; do
    ROUND=$((ROUND + 1))

    # Auto-stop guard: if the system was already shut down (completion/manual), exit quietly
    if [ -f "$LOG_DIR/STOPPED" ]; then
        log "⏹  STOPPED marker found, driver exiting"
        exit 0
    fi

    log "=== ROUND $ROUND ==="
    log "Provider: $(cur_provider)"

    # Save round mark for output detection
    stat -c %s "$LOG" > "$LOG_DIR/.round_mark" 2>/dev/null || echo "0"

    # Check for ALL_DONE → one-stop shutdown (stops watchdog/reports, sends ONE final notification)
    if all_done && tests_pass; then
        log_success "🎉 ALL TASKS COMPLETED AND TESTS PASS → auto-shutdown"
        save_status "COMPLETED"
        auto_commit "All tasks completed"
        "$REPO/shutdown.sh" "all tasks complete (driver)" >> "$LOG" 2>&1 || true
        exit 0
    fi

    # Execute AI agent (skip if dry run)
    if [ "$DRY_RUN" != "true" ]; then
        log "Starting AI agent..."
        # 前台 timeout 模式（默认，推荐）：AI 命令由 timeout 兜底，卡死会被
        # timeout 强制结束，无需额外的零输出熔断，也不会永久阻塞主循环。
        # ⚠️ 若改成后台执行（`... &` + `wait`），timeout 将失效、wait 可能
        #    永久阻塞 —— 必须调用 spawn_stall_watchdog 做循环熔断；绝不能只
        #    `sleep N` 后单次检查（会漏掉“先有输出后卡死”的假死，见函数注释）。
        # Use `|| EXIT_CODE=$?` so a non-zero exit from timeout does NOT trigger
        # `set -e`/ERR trap before we get to inspect the code.
        # Initialize to 0: on success the `||` branch never runs, so without
        # this a successful round would be misread as a failure.
        EXIT_CODE=0
        timeout "$DRIVER_TIMEOUT" pi --print --no-session --mode text --model router/L2 -p '无人值守驱动. 成本铁律: 只读当前工单文件与它点名的文件+必要源码, 禁止通读工程书/全库/无关源码, 每轮 token 都是订阅额度. 读取 docs/tickets 目录,找到编号最小的状态为 pending 且其 Blocked by 引用的工单全部 done 的工单. 严格按该工单实现,遵循 docs/specs 与工程书强制禁止事项,测试驱动开发. 完成后把该工单状态行改为 done,复制该文件到 .unattended/tasks/done 目录,运行 python3 -m pytest tests/ -q 确认全绿,然后 git add -A 并 git commit. 若无可做工单,只输出一行等待原因,禁止修改任何代码禁止提交' >> "$LOG" 2>&1 || EXIT_CODE=$?

        # Handle result
        # GUARD:fail-streak — 保险②: 连续3轮失败 → 熔断停机(人工检查后恢复)
        if [ "${EXIT_CODE:-1}" -eq 0 ]; then
            log_success "Round completed successfully"
            echo 0 > "$LOG_DIR/.fail_streak"
            auto_commit "Auto checkpoint - Round $ROUND"
        else
            # GUARD:quota-pause — 保险①: 仅失败轮才查(router 已自动切智谱兜底,
            # 这里触发=双供应商都额度耗尽), 成功轮输出含"额度"字样不误报
            if quota_hit; then
                RESUME_AT=$(( $(date +%s) + 18000 ))
                echo "$RESUME_AT" > "$LOG_DIR/PAUSED_QUOTA"
                log_error "双供应商额度耗尽(429/quota) → 暂停至 $(date -d @$RESUME_AT '+%F %T'), 窗口重置后自动续跑"
                notify-send --app-name=DF-FanYi --urgency=critical -t 0 \
                    "⏸ DF-FanYi 无人值守暂停" \
                    "MiniMax+智谱额度均耗尽, 5h 窗口重置后自动续跑: $(date -d @$RESUME_AT '+%H:%M')\n工单进度已保存, 无需人工干预" 2>/dev/null || true
                exit 0
            fi
            STREAK=$(( $(cat "$LOG_DIR/.fail_streak" 2>/dev/null || echo 0) + 1 ))
            echo "$STREAK" > "$LOG_DIR/.fail_streak"
            if [ "$STREAK" -ge 3 ]; then
                echo "circuit-break: 连续${STREAK}轮失败 @ $(date '+%F %T'), 详见 driver.log" > "$LOG_DIR/STOPPED"
                log_error "🛑 连续 $STREAK 轮失败 → 熔断停机. 恢复: rm .unattended/STOPPED && bash scripts/install-unattended.sh"
                notify-send --app-name=DF-FanYi --urgency=critical -t 0 \
                    "🛑 DF-FanYi 熔断停机" \
                    "连续 ${STREAK} 轮 agent 失败, 已停机防烧钱\n查看: tail -50 ~/DF-FanYi/.unattended/driver.log\n恢复: rm ~/DF-FanYi/.unattended/STOPPED 后 bash scripts/install-unattended.sh" 2>/dev/null || true
                exit 1
            fi
            if [ "${EXIT_CODE:-1}" -eq 124 ]; then
                log_error "Timeout after $DRIVER_TIMEOUT seconds (fail streak $STREAK/3)"
                save_checkpoint "timeout" "Driver timeout" "Retry next round" "Round $ROUND timeout"
            else
                log_error "Agent failed with code ${EXIT_CODE:-1} (fail streak $STREAK/3)"
            fi
        fi
        unset EXIT_CODE
    fi

    # Detect issues and handle
    if ctx_hit; then
        log "⚠️ Context overflow, starting fresh session"
        save_checkpoint "context_overflow" "Context full" "Restart fresh" "Round $ROUND"
        touch "$LOG_DIR/FRESH_NEXT"
    fi

    # Save status and wait
    save_status "RUNNING"
    log "Round complete, waiting 30s..."
    sleep 30
done

log "=== DRIVER FINISHED ==="
